language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y tahoe-lafs python-qt4

install:
  - pip install coveralls
  - pip install .

script: coverage run --source=gridsync setup.py test

after_success: coveralls

notifications:
  irc:
    channels: "chat.freenode.net#gridsync"
    skip_join: true
    use_notice: true
    template:
      - "[%{repository_name}:%{branch}] %{commit}: %{commit_subject} (%{author}) %{message}"
      - "Details: %{build_url} | Changes: %{compare_url}"

