sudo: required
dist: trusty
os:
  - "linux"
  - "osx"
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get install -y qtbase5-dev python3-pyqt5 python3-pip; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export PATH=/usr/bin:$PATH; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install python pyqt5; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew link --force qt5; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=/usr/local/bin:$PATH; fi
  - sudo python3 -m pip install --upgrade tox coveralls
  - sudo make pyqt 1>/dev/null
before_script:
  - env
  - which python && python --version
  - python -c "from PyQt5 import Qt;print(Qt.QT_VERSION_STR)"
  - python -c "from PyQt5 import Qt;print(Qt.PYQT_VERSION_STR)"
  - which python2 && python --version
  - python2 -c "from PyQt5 import Qt;print(Qt.QT_VERSION_STR)"
  - python2 -c "from PyQt5 import Qt;print(Qt.PYQT_VERSION_STR)"
  - which python3 && python3 --version
  - python3 -c "from PyQt5 import Qt;print(Qt.QT_VERSION_STR)"
  - python3 -c "from PyQt5 import Qt;print(Qt.PYQT_VERSION_STR)"
  - which tox && tox --version
script: tox
after_success:
  - coveralls
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then make all; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then dist/Gridsync.app/Contents/MacOS/gridsync --version; fi
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#gridsync"
    skip_join: true
    use_notice: true
    template:
      - "[%{repository_name}:%{branch}] %{commit}: %{commit_subject} (%{author}) %{message}"
      - "Details: %{build_url} | Changes: %{compare_url}"
