language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y tahoe-lafs python-qt4 python-dbus

install:
  - pip install .

notifications:
  irc:
    channels: "chat.freenode.net#gridsync"

