matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      # https://bugreports.qt.io/browse/QTBUG-64928
      #addons:
      #  apt:
      #    sources:
      #    - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
      #    packages:
      #    - xvfb
    - os: osx
      osx_image: xcode6.4
      #language: python
      #cache: pip
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe" | sudo tee -a /etc/apt/sources.list; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -y update; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -y install build-essential xvfb; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then pyenv install --list; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then pyenv versions; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then pyenv install --skip-existing 2.7.14; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then pyenv install --skip-existing 3.5.4; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then pyenv install --skip-existing 3.6.3; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then pyenv rehash; fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then pyenv global 2.7.14 3.5.4 3.6.3; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then sw_vers; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install python python3; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew upgrade pyenv; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then pyenv install --list; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then pyenv versions; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.5.4; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then pyenv rehash; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then pyenv global 3.5.4; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=/usr/local/bin:~/.pyenv/shims:$PATH; fi
  - pyenv versions
  - echo $PATH
  - which python && python --version
  - which python2 && python2 --version
  - which python2.7 && python2.7 --version
  - which python3 && python3 --version
  #- which python3.5 && python3.5 --version
  - which python3.6 && python3.6 --version
  - python2 -m pip install --upgrade setuptools pip
  - python3 -m pip install --upgrade setuptools pip
  - python3 -m pip install --upgrade tox coveralls
  - which virtualenv && virtualenv --version
script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then python3 -m tox; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then python3 -m tox -e py36-pyqt510,flake8,pylint; fi
  - make all
  - dist/Tahoe-LAFS/tahoe --version-and-path
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then xvfb-run -a dist/Gridsync/gridsync --version; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then dist/Gridsync.app/Contents/MacOS/Gridsync --version; fi
after_success:
  - coveralls
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then python scripts/upload_artifacts.py dist/Gridsync.tar.gz; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then python scripts/upload_artifacts.py dist/Gridsync.dmg; fi
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#gridsync"
    skip_join: true
    use_notice: true
    template:
      - "[%{repository_name}:%{branch}] %{commit}: %{commit_subject} (%{author}) %{message}"
      - "Details: %{build_url} | Changes: %{compare_url}"
before_deploy:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then mv dist/Gridsync.tar.gz dist/Gridsync-Linux.tar.gz; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then mv dist/Gridsync.dmg dist/Gridsync-Mac.dmg; fi
deploy:
  provider: releases
  api_key:
    secure: Sz/ABAcjcGZNuQ7K4KOtZJniW+ICsaxwrS0P2aAzaxrMQT8Ha/hnZ/yavZpI5azzUdC4i48Pu9Rv+OdlHDwPQkBpIIXYRTNlo3fPHSZv344HpTFu1tlJVuB0KXmXG04Abu5anEShV9MFJKrBe9sORBiIr1AQFCF0d5Gi5nVsRHm+kGy1NL4NnzFKJ5mE/yvAMdUXz2wi/lJR2z/0UkJJW6jIXNpsa/2G6HIQelYzAh8rlIJbpWzLWGpMvRlzqS3yl8EwrcCkb2IqVeSSamlq3SwyoinHf8+rlU/W8uiTnyOo5OPhKMknuUlLJkthMsdIUDWQILRd69peLoNAfwFusyvL229tdfLi5YYcRRM5QyQ0Vjy6YYKihwg0LRUg3NDLqA5YCOYszyzm6TzZlsF3niLe+ocIiqhueQdj4QwAMaagO1Ub2rFvrIGmO78oWfA7UzQCutJcZ66ETQyUdTANrDMZAKpwIzprz0v2NFkSyqLi7HkgPKREeV+nxGAVS0Gtw+EO0b3eF9JMJmly/qI+6yA4Rz/PqgLVz94X0fQnU6Eh2IzDhYn31SXo8fVMdxglV5KeStLvA8ofKA3VhVC+6U+u+4OwtIdFNMWZNlTFkT8uqVHcSPfNEU3gVpWu9ObM4e9yNJzcc7Cxx8+oN/+iWVy0BCetMxmQMBriW5vcCXU=
  file_glob: true
  file: dist/Gridsync-*.*
  skip_cleanup: true
  draft: false
  prerelease: true
  on:
    tags: true
env:
  global:
    secure: lUiQR+y0h5mMOgVV2r5vGAMvuG5oMSdJnIeEGJX6HrgQDq7tRqoSGgX4hrAc68MJR4wRSxRm7mdEWeroURlNaLt7cMER8RvL1T4EDnSXSXkCzAtfslU8L2pfzeokrQ+Gpj5mn27yZHFHNk89dsdhFijgQk33p6DScyuT+WAHx2n7+756I6FjD9kz+AnUtwZF1tg9DJs1f+q2vCui+RmuP1pJqDTn9AG7hk0JejO4limPYrQMjL6IsQrL/iB8S7JBfp6LVUGEIfxXV7oBHAScJYrjqT6Lc9EyvCqsL/10p4a4LnYgVSoG0c2urJw310MdzCRUiZSknv7pCxyi6qdUxo+p8yWT+HtT6p0cL15/oc8Lgs81HOFMtpZE2AtEPu/04o5rgYy8X9XvwJkfuDmf+gpIli8/tnU/qQxtnDl5MwNjS6zr82sC09b9d2OSrZm9KcVDecLS9rjsdHluK4MVnSe2/FWuHv2h8U0mHbnxbD5qMeLttHza3Gp9NqRgC/q/EoMH7MBUvJmXRkTx7Ap1ZxZMqTiLQY95E2u3g7Z9rZhBF03+TmoR3OWDyIgN8IsQtrX/6iE7QwWHWkmu9hixzAPWe73BZoksueofnuQoFGdnvuxcpW9i1yYcrJ8ULuMQcZXM4xpNSyttJtHs2O3wYRrw3cnzHygxDGb0Prqtf18=
