sudo: required
dist: trusty
os:
  - "linux"
  - "osx"
install:
  #- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get update; fi
  #- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get install -y qtbase5-dev python3-pyqt5; fi
  #- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then PYTHON='python3' make pyqt 1>/dev/null; fi
  #- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export PATH=/usr/bin:$PATH; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install python3; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install python pyqt5; fi
  #- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew link --force qt5; fi
  - pip2 install --upgrade pip
  - pip3 install --upgrade pip
  - pip3 install tox coveralls || sudo pip3 install tox coveralls
  #- make pyqt 1>/dev/null
before_script:
  - env
  - which python && python --version && which pip && pip --version
  - which python2 && python2 --version && which pip2 && pip2 --version
  - which python3 && python3 --version && which pip3 && pip3 --version
  - which tox && tox --version
script:
  - tox
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then curl --create-dirs -o dist/Tahoe-LAFS.zip https://buildbot.gridsync.io/tahoe-lafs/Tahoe-LAFS-osx.zip; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then make all; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then dist/Gridsync.app/Contents/MacOS/Gridsync --version; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then dist/Gridsync.app/Contents/MacOS/Gridsync --tahoe-version; fi
after_success:
  - coveralls
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#gridsync"
    skip_join: true
    use_notice: true
    template:
      - "[%{repository_name}:%{branch}] %{commit}: %{commit_subject} (%{author}) %{message}"
      - "Details: %{build_url} | Changes: %{compare_url}"
