language: python
sudo: required
dist: trusty
python:
  - "2.7"
env:
  - TOXENV=py27
before_install:
  - sudo apt-get update
  - sudo apt-get install -y tahoe-lafs python-tox python3-pyqt5

virtualenv:
  system_site_packages: true

install:
  - pip install .

script: tox

notifications:
  irc:
    channels: "chat.freenode.net#gridsync"
    skip_join: true
    use_notice: true
    template:
      - "[%{repository_name}:%{branch}] %{commit}: %{commit_subject} (%{author}) %{message}"
      - "Details: %{build_url} | Changes: %{compare_url}"

