language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y tahoe-lafs python-qt4

install:
  - pip install .

script: 
  - make test

notifications:
  irc:
    channels: "chat.freenode.net#gridsync"

